openapi: 3.0.0
info:
  title: Fine-Grained Authorization Service
  description: A microservice for managing fine-grained access control to resources.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local Development Server
tags:
  - name: External
  - name: Internal
paths:
  /authz/{subject_id}:
    get:
      tags:
        - External
      parameters:
        - in : path
          name: subject_id
          description: subject id considered as a user identification
          required: true
          schema:
            type: string
        - in: query
          name: object_id
          schema:
            type: string
        - in: query
          name: action_id
          schema:
            type: string
      responses:
        '200':
          description: Authorization pass
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
  /role/{id}:
    get:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '500':
          description: Internal server error
    put:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
      responses:
        '201':
          description: "Role updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"
    delete:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "Role deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"
  /role:
    get:
      tags:
        - Internal
      parameters:
        - in: query
          name: name
          schema:
            type: string
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '500':
          description: Internal server error
    post:
      tags:
        - Internal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
      responses:
        '201':
          description: "Role created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"

  /action/{id}:
    get:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Action'
        '500':
          description: Internal server error
    put:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Action"
      responses:
        '201':
          description: "Action created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Action"
    delete:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "Action deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Action"
  /action:
    get:
      tags:
        - Internal
      parameters:
        - in: query
          name: name
          schema:
            type: string
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Action'
        '500':
          description: Internal server error
    post:
      tags:
        - Internal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Action"
      responses:
        '201':
          description: "Action created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Action"

  /subject:
    post:
      tags:
        - Internal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Subject"
      responses:
        '201':
          description: "Role created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subject"
  /subject/{subject_id}/{isActive}:
    put:
      tags:
        - Internal
      parameters:
        - name: subject_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: isActive
          in: path
          required: true
          schema:
            type: boolean
      responses:
        '201':
          description: "Action updated"

  /policy/{id}:
    get:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'
        '500':
          description: Internal server error
    put:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        '201':
          description: "Role updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"
    delete:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "Policy deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
  /policy:
    get:
      tags:
        - Internal
      parameters:
        - in: query
          name: name
          schema:
            type: string
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'
        '500':
          description: Internal server error
    post:
      tags:
        - Internal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        '201':
          description: "Policy created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
  /user-role:
    post:
      tags:
        - Internal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRole"
      responses:
        '201':
          description: "User role mapping created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRole"
  /user-role/{id}:
    delete:
      tags:
        - Internal
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "User role deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRole"

components:
  schemas:

    Subject:
      type: object
      properties:
        id:
          type: integer
          format: int64
        subject_id:
          type: string
        class :
          type: string
        status:
          type: string
      required:
        - subject_id
        - class
    Action:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        action_type:
          type: string
      required:
        - name

    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - name

    Policy:
      properties:
        id:
          type: integer
          format: int64
        subject_id:
          type: string
        action_name:
          type: string
        object_id:
          type: string
      required:
        - subject_id
        - action_name
        - object_id

    UserRole:
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: string
        role_id:
          type: string
      required:
        - user_id
        - role_id



