#spring:
#    application:
#        name: dataframe


services:
    cdn:
        baseUrl: "cdn"
    fgaccess:
        baseUrl: ""
    notification:
        baseUrl: ""
    payment:
        baseUrl: ""
    report:
        baseUrl: ""
    state:
        baseUrl: ""