openapi: 3.0.0
info:
  title: Fine-Grained Authorization Service
  description: A microservice for managing fine-grained access control to resources.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local Development Server
tags:
  - name: FGAccess
  - name: Internal
paths:
  /authz/{subject_id}:
    get:
      tags:
        - FGAccess
      operationId: authz
      parameters:
        - in : path
          name: subject_id
          description: subject_id considered as a user identification
          required: true
          schema:
            type: string
        - in: query
          name: object_id
          schema:
            type: string
        - in: query
          name: action_name
          schema:
            type: string
      responses:
        '200':
          description: Authorization pass
        '401':
          description: Authorization failed
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
  /role/{id}:
    get:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
    put:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
      responses:
        '201':
          description: "Role updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"
        '401':
          description: "Unauthorized"
        '404':
          description: Not found.
        '500':
          description: Internal server error
    delete:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: "Role deleted"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
  /role:
    get:
      tags:
        - FGAccess
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '404':
          description: Not found.
        '401':
          description: "Unauthorized"
        '500':
          description: Internal server error
    post:
      tags:
        - FGAccess
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
      responses:
        '201':
          description: "Role created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Role"

        '401':
          description: "Unauthorized"
        '500':
          description: Internal server error

  /action/{id}:
    get:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
    put:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Action"
      responses:
        '201':
          description: "Action updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Action"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
    delete:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: "Action deleted"

        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
  /action:
    get:
      tags:
        - FGAccess
      parameters:
        - in: query
          name: name
          required: false
          schema:
            type: string
        - in: query
          name: type
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Action'
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
    post:
      tags:
        - FGAccess
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Action"
      responses:
        '201':
          description: "Action created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Action"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error

  /subject:
    post:
      tags:
        - FGAccess
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Subject"
      responses:
        '201':
          description: "Role created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subject"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
  /subject/{subject_id}/{isActive}:
    put:
      tags:
        - FGAccess
      parameters:
        - name: subject_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: isActive
          in: path
          required: true
          schema:
            type: boolean
      responses:
        '201':
          description: "Action updated"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error

  /policy/{id}:
    get:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
    put:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        '200':
          description: "Role updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error

    delete:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: "Policy deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
  /policy:
    get:
      tags:
        - FGAccess
      parameters:
        - in: query
          name: subject_id
          schema:
            type: string
        - in: query
          name: action_name
          schema:
            type: string
        - in: query
          name: object_id
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: boolean
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
    post:
      tags:
        - FGAccess
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        '201':
          description: "Policy created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
  /user-role:
    post:
      tags:
        - FGAccess
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRole"
      responses:
        '201':
          description: "User role mapping created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRole"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
  /user-role/{id}:
    delete:
      tags:
        - FGAccess
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "User role deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRole"
        '400':
          description: Bad request.
        '404':
          description: Not found.
        '500':
          description: Internal server error
components:
  schemas:

    Subject:
      type: object
      properties:
        id:
          type: integer
          format: int64
        subject_id:
          type: string
        status:
          type: boolean
      required:
        - subject_id
        - class
    Action:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        action_type:
          type: string
      required:
        - name

    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - name

    Policy:
      properties:
        id:
          type: integer
          format: int64
        subject_id:
          type: string
        action_name:
          type: string
        object_id:
          type: string
        status:
          type: boolean
      required:
        - subject_id


    UserRole:
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: string
        role_id:
          type: integer
          format: int64
      required:
        - user_id
        - role_id



