openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'notification-service'
tags:
  - name: Notification
paths:
  /send:
    post:
      tags:
        - Notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Notification"
      responses:
        '201':
          description: "notification created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notification"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
  /notification:
    get:
      tags:
        - Notification
      parameters:
        - in: query
          name: status
          schema:
            type: string
        - in: query
          name: severity
          schema:
            type: string
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
  /notification/{id}:
    get:
      tags:
        - Notification
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error


  /recipient:
    post:
      tags:
        - Notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Recipient"
      responses:
        '201':
          description: "Recipient created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recipient"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
    delete:
      tags:
        - Notification
      parameters:
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        '200':
          description: "Recipients deleted"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error

  /recipient-group/{name}:
    post:
      tags:
        - Notification
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Recipient"
      responses:
        '201':
          description: "Recipient group created"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
    delete:
      tags:
        - Notification
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Recipient group deleted"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error





components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: integer
          format: int64
        message:
          type: string
        template_name:
          type: string
        subject_placeholders:
          type: array
          items:
            type: string
        body_placeholders:
          type: array
          items:
            type: string
        recipients:
          type: array
          items:
            type: string
        recipient_group:
          type: string
        sent_date:
          type: string
        ack_url:
          type: string
        severity:
          type: string
          enum: ["info","success", "warning", "error"]
        status:
          type: string
          enum: ["pending","sent", "ack","failed"]

    RecipientGroup:
      type: object
      properties:
        id:
          type: integer
          format: int64
        group_name:
          type: string
        recipient_id:
          type: integer
          format: int64
    Recipient:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        device_id:
          type: string
      required:
        - name
    NotificationTemplate:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        subject_template:
          type: string
        body_template:
          type: string

      required:
        - name