openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'notification-service'
tags:
  - name: Notification
paths:
  /notification:
    post:
      tags:
        - Notification
      operationId: saveNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Notification"
      responses:
        '201':
          description: "notification created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notification"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error

    get:
      tags:
        - Notification
      operationId: searchNotification
      parameters:
        - in: query
          name: status
          schema:
            type: string
        - in: query
          name: severity
          schema:
            type: string
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
  /notification/{id}:
    get:
      tags:
        - Notification
      operationId: getById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Okey
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error


  /recipient:
    post:
      tags:
        - Notification
      operationId: save
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Recipient"
      responses:
        '201':
          description: "Recipient created if not exist"

        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
    delete:
      tags:
        - Notification
      operationId: delete
      parameters:
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        '200':
          description: "Recipients deleted"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error

  /group:
    post:
      tags:
        - Notification
      operationId: saveGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                $ref: '#/components/schemas/Group'
      responses:
        '201':
          description: "Group created if not exist"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
  /group/{name}:
    delete:
      operationId: deleteGroup
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Deleted"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error

    post:
      tags:
        - Notification
      operationId: assignRecipientsInGroup
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int64
      responses:
        '201':
          description: "assigned"

        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error




components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: integer
          format: int64
        template_name:
          type: string
        subject_placeholders:
          type: array
          items:
            type: string
        body_placeholders:
          type: array
          items:
            type: string
        recipients:
          type: array
          items:
            type: string
        recipient_group:
          type: string
        severity:
          type: string
          enum: ["info","success", "warning", "error"]


    Recipient:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        device_id:
          type: string
      required:
        - name

    Group:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - name