openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: ''
tags:
  - name: Report

paths:
  /report:
    post:
      tags:
        - Report
      operationId: submitReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Report"
      responses:
        '201':
          description: "Report created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Report"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
  /report/{id}/action/{action}:
    post:
      tags:
        - Report
      operationId: applyAction
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: action
          required: true
          schema:
            type: string
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: "#/components/schemas/Comment"
      responses:
        '200':
          description: "Action updated"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
  /follow/{user_id}/{report_id}:
    post:
      operationId: follow
      tags:
        - Report
      parameters:
        - in: path
          name: report_id
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "followed"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error

  /proposal:
    post:
      tags:
        - Report
      operationId: submitProposal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Proposal"
      responses:
        '201':
          description: "Proposal created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Proposal"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error

  /assign:
    post:
      tags:
        - Report
      operationId: assignReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Assignment"
      responses:
        '201':
          description: "Report assigned"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Report"
        '400':
          description: Bad request.
        '401':
          description: Authorization failed
        '500':
          description: Internal server error
components:
  schemas:
    Report:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        priority:
          type: string
          enum: ["low", "medium", "high"]
        tags:
          type: array
          items:
            type: string
        reporter:
          type: string
        media:
          type: array
          items:
            $ref: '#/components/schemas/MediaContent'
        location:
          type: array
          items:
            $ref: '#/components/schemas/Location'
      required:
        - title
        - reporter
        - description
        - location

    MediaContent:
      type: object
      properties:
        name:
          type: string
        type:
          type: string

    Proposal:
      type: object
      properties:

        report_id:
          type: integer
          format: int64
        user_id:
          type: string
        state:
          type: integer
          format: int64
        action:
          type: string
        amount:
          type: number
      required:
        - report_id
        - user_id
        - amount
        - state
        - action

    Assignment:
      type: object
      properties:

        report_id:
          type: integer
          format: int64
        assign_by:
          type: string
        assign_to:
          type: string
        proposal_id:
          type: integer
          format: int64



    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        report_id:
          type: integer
          format: int64
        user_id:
          type: string
        comments:
          type: string
        parent_comments:
          type: integer
          format: int64
        rank:
          type: integer
      required:
        - report_id
        - user_id
        - comments



    Location:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        lat:
          type: number
        lng:
          type: number
        google_location_url:
          type: string



